# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'
        
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Install dependencies 
      run: npm ci

    - name: Run Tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless
      
    - name: Build
      run: npm run build -- -c production --base-href "https://thecell.github.io/emvs-2024/"
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist/emvs-2024/browser
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      repository-projects: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
